"""
tests.retrieval — retrieval-quality regression suite.

Permanent regression gate for any change that touches the retrieval
pipeline (BM25, FTS, dense vectors, reranker, query rewriter, glossary,
embedding model). Wired into pytest so CI fails the build if a
candidate change degrades Recall@K or NDCG@K beyond tolerance against
the captured baseline.

Files in this package
---------------------
* ``eval_metrics.py``      — pure functions: Recall@K, NDCG@K, MRR.
* ``golden_queries.jsonl`` — one JSON object per line: query text +
                              snapshot of top-K chunk IDs from a
                              known-good production run.
* ``test_retrieval_baseline.py`` — pytest that replays each golden
                              query, runs current orchestrator, and
                              asserts metrics stay within tolerance.

The golden file is regenerated by ``scripts/build_golden_queries.py``
which is intended to be run manually after an intentional retrieval
upgrade ("we're confident the new behaviour is correct → snapshot it
as the new baseline").
"""
